### ISSUE TITLE
[기능 개선] 멀티플레이 게임 오버 후에 후처리

### ISSUE THREAD

**Issue by haileymoon** [CSID-DGU/2021-2-OSSProj-Trex_breeder-10#20]
현재 멀티플레이에 스코어보드가 구현되어있지않다. 따라서 기존 클래식이나 아케이드의 구조인 [게임오버> 플레이어 이름기록> 스코어보드> 홈화면]과 다르게 게임오버가 되었을 때 엔터를 누르면 게임이 종료가 되는 흐름이다.
멀티도 가능하다면 게임오버가 되었을 때 홈화면으로 안내되었으면 한다.

**Comment by cnh12** [comment]
멀티도 아케이드 처럼 스코어보드 간 후에 하는 게 좋지 않을까요?

**Comment by haileymoon** [comment]
> 멀티도 아케이드 처럼 스코어보드 간 후에 하는 게 좋지 않을까요?

네넵 이렇게 작업했습니다
